using System;
using System.Data;
using Microsoft.Data.SqlClient;

namespace TeaEstate
{
    // Member 05 — handles all database work for tea-yield records.
    // OOP: Interfaces — implements the shared IDataManager contract (GetAll + DeleteById).
    // NOTE: 'Date' is a SQL reserved word, so it is always written as [Date].
    public class YieldRepository : IDataManager
    {
        // Return every yield record with friendly worker + section names (for the grid).
        public DataTable GetAll()
        {
            string sql =
                "SELECT y.YieldID, w.Name, s.SectionName, y.Quantity, y.[Date] " +
                "FROM YieldRecord y " +
                "JOIN Worker w ON y.WorkerID = w.WorkerID " +
                "JOIN EstateSection s ON y.SectionID = s.SectionID";

            return DatabaseHelper.ExecuteQuery(sql);
        }

        // Insert a new yield record. YieldID is auto-generated by the DB.
        public void Add(YieldRecord record)
        {
            string sql =
                "INSERT INTO YieldRecord (WorkerID, SectionID, Quantity, [Date]) " +
                "VALUES (@workerId, @sectionId, @quantity, @date)";

            SqlParameter[] p = new SqlParameter[]
            {
                new SqlParameter("@workerId", record.WorkerID),
                new SqlParameter("@sectionId", record.SectionID),
                new SqlParameter("@quantity", record.Quantity),
                new SqlParameter("@date", record.Date)
            };

            DatabaseHelper.ExecuteNonQuery(sql, p);
        }

        // Delete one yield record by its primary key (part of the IDataManager contract).
        public void DeleteById(int id)
        {
            string sql = "DELETE FROM YieldRecord WHERE YieldID = @id";
            SqlParameter[] p = new SqlParameter[] { new SqlParameter("@id", id) };
            DatabaseHelper.ExecuteNonQuery(sql, p);
        }

        // Summary: total quantity picked from each estate section.
        public DataTable TotalBySection()
        {
            string sql =
                "SELECT s.SectionName, SUM(y.Quantity) AS TotalQuantity " +
                "FROM YieldRecord y " +
                "JOIN EstateSection s ON y.SectionID = s.SectionID " +
                "GROUP BY s.SectionName";

            return DatabaseHelper.ExecuteQuery(sql);
        }

        // Summary: total quantity picked by each worker.
        public DataTable TotalByWorker()
        {
            string sql =
                "SELECT w.Name, SUM(y.Quantity) AS TotalQuantity " +
                "FROM YieldRecord y " +
                "JOIN Worker w ON y.WorkerID = w.WorkerID " +
                "GROUP BY w.Name";

            return DatabaseHelper.ExecuteQuery(sql);
        }
    }
}
