using System.Data;
using Microsoft.Data.SqlClient;

namespace TeaEstate
{
    // Member 04 — handles all database work for estate sections.
    // OOP: Interfaces — implements the shared IDataManager contract (GetAll + DeleteById).
    // All DB access goes through Member 01's DatabaseHelper (parameterised = safe).
    public class SectionRepository : IDataManager
    {
        // Return every estate section for showing in a grid.
        public DataTable GetAll()
        {
            // Explicit columns (not SELECT *) so the grid always gets these exact
            // names in this order, matching what SectionForm reads.
            string sql = "SELECT SectionID, SectionName, Area FROM EstateSection ORDER BY SectionName";
            return DatabaseHelper.ExecuteQuery(sql);
        }

        // Insert a new section. SectionID is auto-generated by the DB, so we only send name + area.
        public void Add(EstateSection section)
        {
            string sql = "INSERT INTO EstateSection (SectionName, Area) VALUES (@name, @area)";

            SqlParameter[] p = new SqlParameter[]
            {
                new SqlParameter("@name", section.SectionName),
                new SqlParameter("@area", section.Area)
            };

            DatabaseHelper.ExecuteNonQuery(sql, p);
        }

        // Update an existing section (found by its primary key).
        public void Update(EstateSection section)
        {
            string sql = "UPDATE EstateSection SET SectionName = @name, Area = @area WHERE SectionID = @id";

            SqlParameter[] p = new SqlParameter[]
            {
                new SqlParameter("@name", section.SectionName),
                new SqlParameter("@area", section.Area),
                new SqlParameter("@id", section.SectionID)
            };

            DatabaseHelper.ExecuteNonQuery(sql, p);
        }

        // Delete one section by its primary key (part of the IDataManager contract).
        public void DeleteById(int id)
        {
            string sql = "DELETE FROM EstateSection WHERE SectionID = @id";
            SqlParameter[] p = new SqlParameter[] { new SqlParameter("@id", id) };
            DatabaseHelper.ExecuteNonQuery(sql, p);
        }
    }
}
